In [1]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
arr_float = np.random.rand(4,3)
arr_float

array([[0.1890544 , 0.07294632, 0.24882343],
       [0.39184755, 0.4890572 , 0.66033225],
       [0.54703672, 0.8280138 , 0.88229489],
       [0.50676557, 0.42977265, 0.3139777 ]])

In [3]:
arr_ent = np.random.randint(10,size=(2,3))
arr_ent

array([[2, 6, 4],
       [9, 1, 3]])

In [4]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [5]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [6]:
np.insert(arr, 2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.delete(arr_ent,1,axis=0)

array([[2, 6, 4]])