In [1]:
import numpy as np 

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[19, 88,  9, 95],
       [97, 82, 13, 44],
       [89, 82,  0, 25]])

In [2]:
arr_ent.astype(float)

array([[19., 88.,  9., 95.],
       [97., 82., 13., 44.],
       [89., 82.,  0., 25.]])

In [3]:
arr_ent

array([[19, 88,  9, 95],
       [97, 82, 13, 44],
       [89, 82,  0, 25]])

In [4]:
arr_ent.sort()
arr_ent

array([[ 9, 19, 88, 95],
       [13, 44, 82, 97],
       [ 0, 25, 82, 89]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[ 0, 19, 82, 89],
       [ 9, 25, 82, 95],
       [13, 44, 88, 97]])

In [6]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 0, 19, 82],
       [89,  9, 25],
       [82, 95, 13],
       [44, 88, 97]])

In [7]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 0 19 82]
 [89  9 25]
 [82 95 13]
 [44 88 97]]
[ 0 19 82 89  9 25 82 95 13 44 88 97]


In [8]:
lista_arr = plano_arr.tolist()
lista_arr

[0, 19, 82, 89, 9, 25, 82, 95, 13, 44, 88, 97]

In [9]:
arrays = np.split(arr_ent, 4)
arrays

[array([[ 0, 19, 82]]),
 array([[89,  9, 25]]),
 array([[82, 95, 13]]),
 array([[44, 88, 97]])]

In [12]:
np.concatenate((arrays[1], arrays[0]), axis=1)

array([[89,  9, 25,  0, 19, 82]])

In [11]:
t_arr = arr_ent.T
t_arr

array([[ 0, 89, 82, 44],
       [19,  9, 95, 88],
       [82, 25, 13, 97]])